### ISSUE TITLE
Migrate names.py for italian names/surname

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/commonvoice-it#4]
We need to migrate https://github.com/MozillaItalia/commonvoice-it/blob/master/CommonVoice-Data/names.py 

We need a list of generic names of streets.

**Comment by Mte90** [comment]
We have a dataset from an italian city to use it https://www.dati.gov.it/dataset/elenco-vie

**Comment by lissyx** [comment]
> We have a dataset from an italian city to use it https://www.dati.gov.it/dataset/elenco-vie

I'd welcome any PR augmenting out `names.py` with support for that or adding similar code next to it :)
