### ISSUE TITLE
Autodownload Lingualibre dataset

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/commonvoice-it#8]
https://github.com/MozillaItalia/commonvoice-it/blob/master/DeepSpeech/import_lingualibre.sh needs a way to automatically download and unzip https://lingualibre.fr/datasets/Q385-ita-Italian.zip if the file doesn't exists like for https://github.com/MozillaItalia/commonvoice-it/blob/master/DeepSpeech/import_cvit.sh

**Comment by mone27** [comment]
provo a lavorarci io
